//
// Generated by JTB 1.3.2
//

package spiglet.syntaxtree;

import spiglet.visitor.GJNoArguVisitor;
import spiglet.visitor.GJVisitor;
import spiglet.visitor.GJVoidVisitor;
import spiglet.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> Operator()
 * f1 -> Temp()
 * f2 -> SimpleExp()
 */
public class BinOp implements Node {
    private static final long serialVersionUID = -148038997318201267L;
    public Operator f0;
    public Temp f1;
    public SimpleExp f2;

    public BinOp(Operator n0, Temp n1, SimpleExp n2) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

