//
// Generated by JTB 1.3.2
//

package spiglet.syntaxtree;

import spiglet.visitor.GJNoArguVisitor;
import spiglet.visitor.GJVisitor;
import spiglet.visitor.GJVoidVisitor;
import spiglet.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> "CJUMP"
 * f1 -> Temp()
 * f2 -> Label()
 */
public class CJumpStmt implements Node {
    private static final long serialVersionUID = 1404535814955076782L;
    public NodeToken f0;
    public Temp f1;
    public Label f2;

    public CJumpStmt(NodeToken n0, Temp n1, Label n2) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
    }

    public CJumpStmt(Temp n0, Label n1) {
        f0 = new NodeToken("CJUMP");
        f1 = n0;
        f2 = n1;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

