//
// Generated by JTB 1.3.2
//

package spiglet.syntaxtree;

import spiglet.visitor.GJNoArguVisitor;
import spiglet.visitor.GJVisitor;
import spiglet.visitor.GJVoidVisitor;
import spiglet.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> "HSTORE"
 * f1 -> Temp()
 * f2 -> IntegerLiteral()
 * f3 -> Temp()
 */
public class HStoreStmt implements Node {
    private static final long serialVersionUID = -1756302458150322028L;
    public NodeToken f0;
    public Temp f1;
    public IntegerLiteral f2;
    public Temp f3;

    public HStoreStmt(NodeToken n0, Temp n1, IntegerLiteral n2, Temp n3) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
        f3 = n3;
    }

    public HStoreStmt(Temp n0, IntegerLiteral n1, Temp n2) {
        f0 = new NodeToken("HSTORE");
        f1 = n0;
        f2 = n1;
        f3 = n2;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

