//
// Generated by JTB 1.3.2
//

package spiglet.syntaxtree;

import spiglet.visitor.GJNoArguVisitor;
import spiglet.visitor.GJVisitor;
import spiglet.visitor.GJVoidVisitor;
import spiglet.visitor.Visitor;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
    void accept(Visitor v);

    <R, A> R accept(GJVisitor<R, A> v, A argu);

    <R> R accept(GJNoArguVisitor<R> v);

    <A> void accept(GJVoidVisitor<A> v, A argu);
}

