//
// Generated by JTB 1.3.2
//

package spiglet.syntaxtree;

import spiglet.visitor.GJNoArguVisitor;
import spiglet.visitor.GJVisitor;
import spiglet.visitor.GJVoidVisitor;
import spiglet.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> "BEGIN"
 * f1 -> StmtList()
 * f2 -> "RETURN"
 * f3 -> SimpleExp()
 * f4 -> "END"
 */
public class StmtExp implements Node {
    private static final long serialVersionUID = 133344464190372158L;
    public NodeToken f0;
    public StmtList f1;
    public NodeToken f2;
    public SimpleExp f3;
    public NodeToken f4;

    public StmtExp(NodeToken n0, StmtList n1, NodeToken n2, SimpleExp n3,
                   NodeToken n4) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
        f3 = n3;
        f4 = n4;
    }

    public StmtExp(StmtList n0, SimpleExp n1) {
        f0 = new NodeToken("BEGIN");
        f1 = n0;
        f2 = new NodeToken("RETURN");
        f3 = n1;
        f4 = new NodeToken("END");
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

