//
// Generated by JTB 1.3.2
//

package kanga.syntaxtree;

import kanga.visitor.GJNoArguVisitor;
import kanga.visitor.GJVisitor;
import kanga.visitor.GJVoidVisitor;
import kanga.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> Operator()
 * f1 -> Reg()
 * f2 -> SimpleExp()
 */
public class BinOp implements Node {
    private static final long serialVersionUID = 8971079448852178145L;
    public Operator f0;
    public Reg f1;
    public SimpleExp f2;

    public BinOp(Operator n0, Reg n1, SimpleExp n2) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

