//
// Generated by JTB 1.3.2
//

package kanga.syntaxtree;

import kanga.visitor.GJNoArguVisitor;
import kanga.visitor.GJVisitor;
import kanga.visitor.GJVoidVisitor;
import kanga.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> "CALL"
 * f1 -> SimpleExp()
 */
public class CallStmt implements Node {
    private static final long serialVersionUID = -5772530507040897869L;
    public NodeToken f0;
    public SimpleExp f1;

    public CallStmt(NodeToken n0, SimpleExp n1) {
        f0 = n0;
        f1 = n1;
    }

    public CallStmt(SimpleExp n0) {
        f0 = new NodeToken("CALL");
        f1 = n0;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

