//
// Generated by JTB 1.3.2
//

package kanga.syntaxtree;

import kanga.visitor.GJNoArguVisitor;
import kanga.visitor.GJVisitor;
import kanga.visitor.GJVoidVisitor;
import kanga.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> "HSTORE"
 * f1 -> Reg()
 * f2 -> IntegerLiteral()
 * f3 -> Reg()
 */
public class HStoreStmt implements Node {
    private static final long serialVersionUID = 5047962464133191640L;
    public NodeToken f0;
    public Reg f1;
    public IntegerLiteral f2;
    public Reg f3;

    public HStoreStmt(NodeToken n0, Reg n1, IntegerLiteral n2, Reg n3) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
        f3 = n3;
    }

    public HStoreStmt(Reg n0, IntegerLiteral n1, Reg n2) {
        f0 = new NodeToken("HSTORE");
        f1 = n0;
        f2 = n1;
        f3 = n2;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

