//
// Generated by JTB 1.3.2
//

package kanga.syntaxtree;

import kanga.visitor.GJNoArguVisitor;
import kanga.visitor.GJVisitor;
import kanga.visitor.GJVoidVisitor;
import kanga.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> "MOVE"
 * f1 -> Reg()
 * f2 -> Exp()
 */
public class MoveStmt implements Node {
    private static final long serialVersionUID = 2179179599919619452L;
    public NodeToken f0;
    public Reg f1;
    public Exp f2;

    public MoveStmt(NodeToken n0, Reg n1, Exp n2) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
    }

    public MoveStmt(Reg n0, Exp n1) {
        f0 = new NodeToken("MOVE");
        f1 = n0;
        f2 = n1;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

