//
// Generated by JTB 1.3.2
//

package kanga.syntaxtree;

import kanga.visitor.GJNoArguVisitor;
import kanga.visitor.GJVisitor;
import kanga.visitor.GJVoidVisitor;
import kanga.visitor.Visitor;

/**
 * The interface which NodeList, NodeListOptional, and NodeSequence
 * implement.
 */
public interface NodeListInterface extends Node {
    void addNode(Node n);

    Node elementAt(int i);

    java.util.Enumeration<Node> elements();

    int size();

    @Override
    void accept(Visitor v);

    @Override
    <R, A> R accept(GJVisitor<R, A> v, A argu);

    @Override
    <R> R accept(GJNoArguVisitor<R> v);

    @Override
    <A> void accept(GJVoidVisitor<A> v, A argu);
}

