//
// Generated by JTB 1.3.2
//

package kanga.syntaxtree;

import kanga.visitor.GJNoArguVisitor;
import kanga.visitor.GJVisitor;
import kanga.visitor.GJVoidVisitor;
import kanga.visitor.Visitor;

/**
 * Represents a grammar choice, e.g. ( A | B )
 */
public class NodeChoice implements Node {
    private static final long serialVersionUID = 368599508421212131L;
    public Node choice;
    public int which;

    public NodeChoice(Node node) {
        this(node, -1);
    }

    public NodeChoice(Node node, int whichChoice) {
        choice = node;
        which = whichChoice;
    }

    @Override
    public void accept(Visitor v) {
        choice.accept(v);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return choice.accept(v, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return choice.accept(v);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        choice.accept(v, argu);
    }
}

