//
// Generated by JTB 1.3.2
//

package kanga.syntaxtree;

import kanga.visitor.GJNoArguVisitor;
import kanga.visitor.GJVisitor;
import kanga.visitor.GJVoidVisitor;
import kanga.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> "PASSARG"
 * f1 -> IntegerLiteral()
 * f2 -> Reg()
 */
public class PassArgStmt implements Node {
    private static final long serialVersionUID = 6599986778606238482L;
    public NodeToken f0;
    public IntegerLiteral f1;
    public Reg f2;

    public PassArgStmt(NodeToken n0, IntegerLiteral n1, Reg n2) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
    }

    public PassArgStmt(IntegerLiteral n0, Reg n1) {
        f0 = new NodeToken("PASSARG");
        f1 = n0;
        f2 = n1;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

