//
// Generated by JTB 1.3.2
//

package kanga.syntaxtree;

import kanga.visitor.GJNoArguVisitor;
import kanga.visitor.GJVisitor;
import kanga.visitor.GJVoidVisitor;
import kanga.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> "SPILLEDARG"
 * f1 -> IntegerLiteral()
 */
public class SpilledArg implements Node {
    private static final long serialVersionUID = -5920865201406597806L;
    public NodeToken f0;
    public IntegerLiteral f1;

    public SpilledArg(NodeToken n0, IntegerLiteral n1) {
        f0 = n0;
        f1 = n1;
    }

    public SpilledArg(IntegerLiteral n0) {
        f0 = new NodeToken("SPILLEDARG");
        f1 = n0;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

