//
// Generated by JTB 1.3.2
//

package minijava.syntaxtree;

import minijava.visitor.GJNoArguVisitor;
import minijava.visitor.GJVisitor;
import minijava.visitor.GJVoidVisitor;
import minijava.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> PrimaryExpression()
 * f1 -> "&&"
 * f2 -> PrimaryExpression()
 */
public class AndExpression implements Node {
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    public PrimaryExpression f0;
    public NodeToken f1;
    public PrimaryExpression f2;

    public AndExpression(PrimaryExpression n0, NodeToken n1,
                         PrimaryExpression n2) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
    }

    public AndExpression(PrimaryExpression n0, PrimaryExpression n1) {
        f0 = n0;
        f1 = new NodeToken("&&");
        f2 = n1;
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

