//
// Generated by JTB 1.3.2
//

package minijava.visitor;

import minijava.syntaxtree.*;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

    //
    // GJ void Auto class visitors
    //

    void visit(NodeList n, A argu);

    void visit(NodeListOptional n, A argu);

    void visit(NodeOptional n, A argu);

    void visit(NodeSequence n, A argu);

    void visit(NodeToken n, A argu);

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> MainClass()
     * f1 -> ( TypeDeclaration() )*
     * f2 -> <EOF>
     */
    void visit(Goal n, A argu);

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "{"
     * f3 -> "public"
     * f4 -> "static"
     * f5 -> "void"
     * f6 -> "main"
     * f7 -> "("
     * f8 -> "String"
     * f9 -> "["
     * f10 -> "]"
     * f11 -> Identifier()
     * f12 -> ")"
     * f13 -> "{"
     * f14 -> ( VarDeclaration() )*
     * f15 -> ( Statement() )*
     * f16 -> "}"
     * f17 -> "}"
     */
    void visit(MainClass n, A argu);

    /**
     * f0 -> ClassDeclaration()
     * | ClassExtendsDeclaration()
     */
    void visit(TypeDeclaration n, A argu);

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "{"
     * f3 -> ( VarDeclaration() )*
     * f4 -> ( MethodDeclaration() )*
     * f5 -> "}"
     */
    void visit(ClassDeclaration n, A argu);

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "extends"
     * f3 -> Identifier()
     * f4 -> "{"
     * f5 -> ( VarDeclaration() )*
     * f6 -> ( MethodDeclaration() )*
     * f7 -> "}"
     */
    void visit(ClassExtendsDeclaration n, A argu);

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     * f2 -> ";"
     */
    void visit(VarDeclaration n, A argu);

    /**
     * f0 -> "public"
     * f1 -> Type()
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( FormalParameterList() )?
     * f5 -> ")"
     * f6 -> "{"
     * f7 -> ( VarDeclaration() )*
     * f8 -> ( Statement() )*
     * f9 -> "return"
     * f10 -> Expression()
     * f11 -> ";"
     * f12 -> "}"
     */
    void visit(MethodDeclaration n, A argu);

    /**
     * f0 -> FormalParameter()
     * f1 -> ( FormalParameterRest() )*
     */
    void visit(FormalParameterList n, A argu);

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     */
    void visit(FormalParameter n, A argu);

    /**
     * f0 -> ","
     * f1 -> FormalParameter()
     */
    void visit(FormalParameterRest n, A argu);

    /**
     * f0 -> ArrayType()
     * | BooleanType()
     * | IntegerType()
     * | Identifier()
     */
    void visit(Type n, A argu);

    /**
     * f0 -> "int"
     * f1 -> "["
     * f2 -> "]"
     */
    void visit(ArrayType n, A argu);

    /**
     * f0 -> "boolean"
     */
    void visit(BooleanType n, A argu);

    /**
     * f0 -> "int"
     */
    void visit(IntegerType n, A argu);

    /**
     * f0 -> Block()
     * | AssignmentStatement()
     * | ArrayAssignmentStatement()
     * | IfStatement()
     * | WhileStatement()
     * | PrintStatement()
     */
    void visit(Statement n, A argu);

    /**
     * f0 -> "{"
     * f1 -> ( Statement() )*
     * f2 -> "}"
     */
    void visit(Block n, A argu);

    /**
     * f0 -> Identifier()
     * f1 -> "="
     * f2 -> Expression()
     * f3 -> ";"
     */
    void visit(AssignmentStatement n, A argu);

    /**
     * f0 -> Identifier()
     * f1 -> "["
     * f2 -> Expression()
     * f3 -> "]"
     * f4 -> "="
     * f5 -> Expression()
     * f6 -> ";"
     */
    void visit(ArrayAssignmentStatement n, A argu);

    /**
     * f0 -> "if"
     * f1 -> "("
     * f2 -> Expression()
     * f3 -> ")"
     * f4 -> Statement()
     * f5 -> "else"
     * f6 -> Statement()
     */
    void visit(IfStatement n, A argu);

    /**
     * f0 -> "while"
     * f1 -> "("
     * f2 -> Expression()
     * f3 -> ")"
     * f4 -> Statement()
     */
    void visit(WhileStatement n, A argu);

    /**
     * f0 -> "System.out.println"
     * f1 -> "("
     * f2 -> Expression()
     * f3 -> ")"
     * f4 -> ";"
     */
    void visit(PrintStatement n, A argu);

    /**
     * f0 -> AndExpression()
     * | CompareExpression()
     * | PlusExpression()
     * | MinusExpression()
     * | TimesExpression()
     * | ArrayLookup()
     * | ArrayLength()
     * | MessageSend()
     * | PrimaryExpression()
     */
    void visit(Expression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "&&"
     * f2 -> PrimaryExpression()
     */
    void visit(AndExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "<"
     * f2 -> PrimaryExpression()
     */
    void visit(CompareExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "+"
     * f2 -> PrimaryExpression()
     */
    void visit(PlusExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "-"
     * f2 -> PrimaryExpression()
     */
    void visit(MinusExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "*"
     * f2 -> PrimaryExpression()
     */
    void visit(TimesExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "["
     * f2 -> PrimaryExpression()
     * f3 -> "]"
     */
    void visit(ArrayLookup n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "."
     * f2 -> "length"
     */
    void visit(ArrayLength n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "."
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( ExpressionList() )?
     * f5 -> ")"
     */
    void visit(MessageSend n, A argu);

    /**
     * f0 -> Expression()
     * f1 -> ( ExpressionRest() )*
     */
    void visit(ExpressionList n, A argu);

    /**
     * f0 -> ","
     * f1 -> Expression()
     */
    void visit(ExpressionRest n, A argu);

    /**
     * f0 -> IntegerLiteral()
     * | TrueLiteral()
     * | FalseLiteral()
     * | Identifier()
     * | ThisExpression()
     * | ArrayAllocationExpression()
     * | AllocationExpression()
     * | NotExpression()
     * | BracketExpression()
     */
    void visit(PrimaryExpression n, A argu);

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    void visit(IntegerLiteral n, A argu);

    /**
     * f0 -> "true"
     */
    void visit(TrueLiteral n, A argu);

    /**
     * f0 -> "false"
     */
    void visit(FalseLiteral n, A argu);

    /**
     * f0 -> <IDENTIFIER>
     */
    void visit(Identifier n, A argu);

    /**
     * f0 -> "this"
     */
    void visit(ThisExpression n, A argu);

    /**
     * f0 -> "new"
     * f1 -> "int"
     * f2 -> "["
     * f3 -> Expression()
     * f4 -> "]"
     */
    void visit(ArrayAllocationExpression n, A argu);

    /**
     * f0 -> "new"
     * f1 -> Identifier()
     * f2 -> "("
     * f3 -> ")"
     */
    void visit(AllocationExpression n, A argu);

    /**
     * f0 -> "!"
     * f1 -> Expression()
     */
    void visit(NotExpression n, A argu);

    /**
     * f0 -> "("
     * f1 -> Expression()
     * f2 -> ")"
     */
    void visit(BracketExpression n, A argu);

}

