//
// Generated by JTB 1.3.2
//

package minijava.visitor;

import minijava.syntaxtree.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

    //
    // void Auto class visitors
    //

    void visit(NodeList n);

    void visit(NodeListOptional n);

    void visit(NodeOptional n);

    void visit(NodeSequence n);

    void visit(NodeToken n);

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> MainClass()
     * f1 -> ( TypeDeclaration() )*
     * f2 -> <EOF>
     */
    void visit(Goal n);

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "{"
     * f3 -> "public"
     * f4 -> "static"
     * f5 -> "void"
     * f6 -> "main"
     * f7 -> "("
     * f8 -> "String"
     * f9 -> "["
     * f10 -> "]"
     * f11 -> Identifier()
     * f12 -> ")"
     * f13 -> "{"
     * f14 -> ( VarDeclaration() )*
     * f15 -> ( Statement() )*
     * f16 -> "}"
     * f17 -> "}"
     */
    void visit(MainClass n);

    /**
     * f0 -> ClassDeclaration()
     * | ClassExtendsDeclaration()
     */
    void visit(TypeDeclaration n);

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "{"
     * f3 -> ( VarDeclaration() )*
     * f4 -> ( MethodDeclaration() )*
     * f5 -> "}"
     */
    void visit(ClassDeclaration n);

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "extends"
     * f3 -> Identifier()
     * f4 -> "{"
     * f5 -> ( VarDeclaration() )*
     * f6 -> ( MethodDeclaration() )*
     * f7 -> "}"
     */
    void visit(ClassExtendsDeclaration n);

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     * f2 -> ";"
     */
    void visit(VarDeclaration n);

    /**
     * f0 -> "public"
     * f1 -> Type()
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( FormalParameterList() )?
     * f5 -> ")"
     * f6 -> "{"
     * f7 -> ( VarDeclaration() )*
     * f8 -> ( Statement() )*
     * f9 -> "return"
     * f10 -> Expression()
     * f11 -> ";"
     * f12 -> "}"
     */
    void visit(MethodDeclaration n);

    /**
     * f0 -> FormalParameter()
     * f1 -> ( FormalParameterRest() )*
     */
    void visit(FormalParameterList n);

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     */
    void visit(FormalParameter n);

    /**
     * f0 -> ","
     * f1 -> FormalParameter()
     */
    void visit(FormalParameterRest n);

    /**
     * f0 -> ArrayType()
     * | BooleanType()
     * | IntegerType()
     * | Identifier()
     */
    void visit(Type n);

    /**
     * f0 -> "int"
     * f1 -> "["
     * f2 -> "]"
     */
    void visit(ArrayType n);

    /**
     * f0 -> "boolean"
     */
    void visit(BooleanType n);

    /**
     * f0 -> "int"
     */
    void visit(IntegerType n);

    /**
     * f0 -> Block()
     * | AssignmentStatement()
     * | ArrayAssignmentStatement()
     * | IfStatement()
     * | WhileStatement()
     * | PrintStatement()
     */
    void visit(Statement n);

    /**
     * f0 -> "{"
     * f1 -> ( Statement() )*
     * f2 -> "}"
     */
    void visit(Block n);

    /**
     * f0 -> Identifier()
     * f1 -> "="
     * f2 -> Expression()
     * f3 -> ";"
     */
    void visit(AssignmentStatement n);

    /**
     * f0 -> Identifier()
     * f1 -> "["
     * f2 -> Expression()
     * f3 -> "]"
     * f4 -> "="
     * f5 -> Expression()
     * f6 -> ";"
     */
    void visit(ArrayAssignmentStatement n);

    /**
     * f0 -> "if"
     * f1 -> "("
     * f2 -> Expression()
     * f3 -> ")"
     * f4 -> Statement()
     * f5 -> "else"
     * f6 -> Statement()
     */
    void visit(IfStatement n);

    /**
     * f0 -> "while"
     * f1 -> "("
     * f2 -> Expression()
     * f3 -> ")"
     * f4 -> Statement()
     */
    void visit(WhileStatement n);

    /**
     * f0 -> "System.out.println"
     * f1 -> "("
     * f2 -> Expression()
     * f3 -> ")"
     * f4 -> ";"
     */
    void visit(PrintStatement n);

    /**
     * f0 -> AndExpression()
     * | CompareExpression()
     * | PlusExpression()
     * | MinusExpression()
     * | TimesExpression()
     * | ArrayLookup()
     * | ArrayLength()
     * | MessageSend()
     * | PrimaryExpression()
     */
    void visit(Expression n);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "&&"
     * f2 -> PrimaryExpression()
     */
    void visit(AndExpression n);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "<"
     * f2 -> PrimaryExpression()
     */
    void visit(CompareExpression n);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "+"
     * f2 -> PrimaryExpression()
     */
    void visit(PlusExpression n);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "-"
     * f2 -> PrimaryExpression()
     */
    void visit(MinusExpression n);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "*"
     * f2 -> PrimaryExpression()
     */
    void visit(TimesExpression n);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "["
     * f2 -> PrimaryExpression()
     * f3 -> "]"
     */
    void visit(ArrayLookup n);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "."
     * f2 -> "length"
     */
    void visit(ArrayLength n);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "."
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( ExpressionList() )?
     * f5 -> ")"
     */
    void visit(MessageSend n);

    /**
     * f0 -> Expression()
     * f1 -> ( ExpressionRest() )*
     */
    void visit(ExpressionList n);

    /**
     * f0 -> ","
     * f1 -> Expression()
     */
    void visit(ExpressionRest n);

    /**
     * f0 -> IntegerLiteral()
     * | TrueLiteral()
     * | FalseLiteral()
     * | Identifier()
     * | ThisExpression()
     * | ArrayAllocationExpression()
     * | AllocationExpression()
     * | NotExpression()
     * | BracketExpression()
     */
    void visit(PrimaryExpression n);

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    void visit(IntegerLiteral n);

    /**
     * f0 -> "true"
     */
    void visit(TrueLiteral n);

    /**
     * f0 -> "false"
     */
    void visit(FalseLiteral n);

    /**
     * f0 -> <IDENTIFIER>
     */
    void visit(Identifier n);

    /**
     * f0 -> "this"
     */
    void visit(ThisExpression n);

    /**
     * f0 -> "new"
     * f1 -> "int"
     * f2 -> "["
     * f3 -> Expression()
     * f4 -> "]"
     */
    void visit(ArrayAllocationExpression n);

    /**
     * f0 -> "new"
     * f1 -> Identifier()
     * f2 -> "("
     * f3 -> ")"
     */
    void visit(AllocationExpression n);

    /**
     * f0 -> "!"
     * f1 -> Expression()
     */
    void visit(NotExpression n);

    /**
     * f0 -> "("
     * f1 -> Expression()
     * f2 -> ")"
     */
    void visit(BracketExpression n);

}

