//
// Generated by JTB 1.3.2
//

package minijava.syntaxtree;

import minijava.visitor.*;

/**
 * Grammar production:
 * f0 -> FormalParameter()
 * f1 -> ( FormalParameterRest() )*
 */
public class FormalParameterList implements Node {
   /**
    *
    */
   private static final long serialVersionUID = 1L;
   public FormalParameter f0;
   public NodeListOptional f1;

   public FormalParameterList(FormalParameter n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

